### ISSUE TITLE
Equipment List

### ISSUE THREAD

**Issue by mjack24** [datagod/gpsprobe#2]
Do you have a list of everything that you need for this project?

**Comment by datagod** [comment]
Yes I do.

1.  Raspberry Pi  (I suggest 3B or higher)
2.  USB Wifi antenna capable of going into monitor mode.  I use an Alfa USB model. 
    https://www.wirelesshack.org/best-kali-linux-compatible-usb-adapter-dongles.html
3.  Unicornhat HD  (16x16 led display)  -- also optional. 
4.  GPS USB dongle from Microsoft Streets and Trips, circa 2003.  It is old, but it works great.  Also optional.

That's about it.
